# Save as: .github/workflows/check-secrets.yml

name: Check Secrets

on:
  workflow_dispatch:  # Manual trigger
  pull_request:
    branches: [ main ]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Check PyPI token
      run: |
        if [ "${{ secrets.PYPI_API_TOKEN }}" = "" ]; then
          echo "::error::PyPI API token is not set. Please add PYPI_API_TOKEN to repository secrets."
          exit 1
        else
          echo "PyPI API token is set correctly."
        fi
      
    - name: Verify token format
      run: |
        TOKEN="${{ secrets.PYPI_API_TOKEN }}"
        if [[ ! $TOKEN =~ ^pypi-[A-Za-z0-9_-]+$ ]]; then
          echo "::error::PyPI API token format appears incorrect. Token should start with 'pypi-'"
          exit 1
        else
          echo "PyPI API token format appears correct."
        fi